//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RLDCReport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChecklistItem
    {
        public Nullable<int> ChecklistId { get; set; }
        public int ChecklistItemId { get; set; }
        public string ItemName { get; set; }
    }
}
